### ISSUE TITLE
Crashing for users with missing home directories

### ISSUE THREAD

**Issue by nickjer** [OSC/ood-dashboard#280]
University of Arizona has the strange scenario that the user's home directories are not created until they login through the PAM module with the following feature:

```
session     required      pam_oddjob_mkhomedir.so skel=/etc/skel/ umask=0022
```

But their OnDemand portal uses the University of Arizona's CAS server for authentication through mod_shib. So when a new user accesses OnDemand first they get the Passenger error message:

> We're sorry, but something went wrong.

One suggestion by Ric is if OOD cannot create the home directory for the user, maybe it can handle the missing home directory more gracefully and provide a helpful message to the user. This seems like a do-able solution, but not sure how we can easily test it.

**Comment by nickjer** [comment]
The log file for a user with no home directory looks like:

```
[ 2017-11-01 12:19:55.4192 119215/7f735fecb720 agents/Watchdog/Main.cpp:728 ]: All Phusion Passenger agents started!
App 119239 stdout: 
[ 2017-11-01 12:19:55.5306 119218/7f53207c7700 Pool2/Implementation.cpp:213 ]: Cannot render an error page: Cannot generate a temporary filename: Permission denied (errno=13)
     in 'void Passenger::ApplicationPool2::processAndLogNewSpawnException(Passenger::SpawnException&, const Passenger::ApplicationPool2::Options&, const Passenger::ApplicationPool2::SpawnerConfigPtr&)' (Implementation.cpp:190)
     in 'void Passenger::ApplicationPool2::Spawner::handleSpawnErrorResponse(Passenger::ApplicationPool2::Spawner::NegotiationDetails&)' (Spawner.h:1341)
     in 'Passenger::ApplicationPool2::ProcessPtr Passenger::ApplicationPool2::Spawner::negotiateSpawn(Passenger::ApplicationPool2::Spawner::NegotiationDetails&)' (Spawner.h:1304)
     in 'virtual Passenger::ApplicationPool2::ProcessPtr Passenger::ApplicationPool2::DirectSpawner::spawn(const Passenger::ApplicationPool2::Options&)' (DirectSpawner.h:203)
     in 'void Passenger::ApplicationPool2::Group::spawnThreadRealMain(const Passenger::ApplicationPool2::SpawnerPtr&, const Passenger::ApplicationPool2::Options&, unsigned int)' (Implementation.cpp:977)

[ 2017-11-01 12:19:55.5307 119218/7f53207c7700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /var/www/ood/apps/sys/dashboard: An error occured while starting the web application.
  Error ID: b772919a
  Message from application: undefined method `+' for nil:NilClass (NoMethodError)
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/path_support.rb:78:in `path='
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/path_support.rb:34:in `initialize'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems.rb:332:in `new'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems.rb:332:in `paths'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems.rb:355:in `path'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:870:in `dirs'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:748:in `stubs'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/specification.rb:936:in `find_inactive_by_path'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems.rb:187:in `try_activate'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:39:in `require'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/native_support.rb:389:in `load_native_extension'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/native_support.rb:116:in `load_from_load_path'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/native_support.rb:37:in `try_load'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/native_support.rb:47:in `start'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/native_support.rb:405:in `<top (required)>'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/rh/rh-ruby22/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:54:in `require'
  /opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger.rb:237:in `require_passenger_lib'
  /opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/rack-loader.rb:73:in `init_passenger'
  /opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/rack-loader.rb:126:in `<module:App>'
  /opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/rack-loader.rb:27:in `<module:PhusionPassenger>'
  /opt/rh/rh-passenger40/root/usr/share/passenger/helper-scripts/rack-loader.rb:26:in `<main>'


[ 2017-11-01 12:19:55.5337 119218/7f531a210700 agents/HelperAgent/RequestHandler.h:2306 ]: [Client 23] Cannot checkout session because a spawning error occurred. The identifier of the error is b772919a. Please see earlier logs for details about the error.
```

**Comment by nickjer** [comment]
This seems to be an issue that goes as deep as the Software Collections ruby installation. As it tries to include sub-directories under the user's `HOME` directory to the gem load path.

So you'd have to catch this issue before any ruby code is called (in particular Passenger).

**Comment by nickjer** [comment]
Simplest solution is modifying `nginx_stage` to check if a user has a home directory and return an error if he/she doesn't. This will throw up the simple text error in the user's browser, but for now it is far more helpful than the above.

**Comment by nickjer** [comment]
Thoughts @ericfranz ?

**Comment by ericfranz** [comment]
Error works. Can look into enhancing the look and feel of the error later. Is it worth making this error msg configurable?

**Comment by ericfranz** [comment]
It's worth asking the external site facing this problem what would be adequate.

**Comment by nickjer** [comment]
This issue is moved to the `nginx_stage` repo.
