### ISSUE TITLE
Template crash on init dashboard display (undef method titleize for Symbol)

### ISSUE THREAD

**Issue by tutufan** [OSC/ood-dashboard#395]
I'm trying to install from RPMs on RHEL 7.5.  On initial login, get a HTTP 500 error.  The backtrace looks like this:

```
App 171763 stdout: [2018-08-27 14:43:56 -0700 ]  INFO "method=GET path=/pun/sys/dashboard/ format=html controller=DashboardController action=index status=
500 error='ActionView::Template::Error: undefined method `titleize' for :talapas:Symbol' duration=18.08 view=0.00"

App 171763 stdout: [2018-08-27 14:43:56 -0700 ] FATAL "ActionView::Template::Error (undefined method `titleize' for :talapas:Symbol):
     5:       <%= content_tag \"li\", \"\", class: \"divider\", role: \"separator\" if index > 0 %>
     6:       <%= content_tag \"li\", g.title, class: \"dropdown-header\" unless g.title.empty? %>
     7:       <% g.apps.each do |app| %>
     8:         <% app.links.each do |link| %>
     9:           <li>
    10:        <%=
    11:               link_to(
  app/apps/ood_app.rb:103:in `block in links'
  app/apps/ood_app.rb:101:in `map'
  app/apps/ood_app.rb:101:in `links'
  app/views/layouts/nav/_group.html.erb:8:in `block (2 levels) in _app_views_layouts_nav__group_html_erb___757112546030436231_34670020'
  app/views/layouts/nav/_group.html.erb:7:in `each'
  app/views/layouts/nav/_group.html.erb:7:in `block in _app_views_layouts_nav__group_html_erb___757112546030436231_34670020'
  app/views/layouts/nav/_group.html.erb:4:in `each'
  app/views/layouts/nav/_group.html.erb:4:in `each_with_index'
  app/views/layouts/nav/_group.html.erb:4:in `_app_views_layouts_nav__group_html_erb___757112546030436231_34670020'
  app/views/layouts/application.html.erb:29:in `_app_views_layouts_application_html_erb___3805025695244590702_34892140'"

App 171763 stdout: [2018-08-27 14:43:56 -0700 ]  INFO "method=GET path=/pun/sys/dashboard/500 format=html controller=ErrorsController action=internal_serv
er_error status=500 error='ActionView::Template::Error: undefined method `titleize' for :talapas:Symbol' duration=7.78 view=0.00"
App 171763 stderr: Error during failsafe response: undefined method `titleize' for :talapas:Symbol
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/apps/ood_app.rb:103:in `block in links'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/clusters.rb:111:in `each'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/ood_core-0.5.1/lib/ood_core/clusters.rb:111:in `each'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/apps/ood_app.rb:101:in `map'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/apps/ood_app.rb:101:in `links'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:8:in `block (2 levels) in _app_views_layouts_nav__group_html_er
b___757112546030436231_34670020'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:7:in `each'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:7:in `block in _app_views_layouts_nav__group_html_erb___7571125
46030436231_34670020'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:4:in `each'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:4:in `each_with_index'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/nav/_group.html.erb:4:in `_app_views_layouts_nav__group_html_erb___7571125460304362
31_34670020'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:145:in `block in render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:333:in `instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:143:in `render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:436:in `block
in collection_with_template'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:432:in `map'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:432:in `collec
tion_with_template'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:324:in `render
_collection'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:306:in `block
in render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/abstract_renderer.rb:39:in `block
in instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/abstract_renderer.rb:39:in `instru
ment'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/partial_renderer.rb:305:in `render
'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:51:in `render_partial'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/renderer/renderer.rb:25:in `render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/helpers/rendering_helper.rb:32:in `render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/app/views/layouts/application.html.erb:29:in `_app_views_layouts_application_html_erb___3805025695244
590702_34892140'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:145:in `block in render'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.10/lib/active_support/notifications.rb:166:in `instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:333:in `instrument'
App 171763 stderr:   /var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.10/lib/action_view/template.rb:143:in `render'

(etc)
```

The significance of `talapas` is that it's part of the hostname, which is `talapas-ln2`.  As a wild guess, maybe some part of the code assumes that hostnames won't have hyphens in them?

Any ideas?

**Comment by ericfranz** [comment]
Just wanted to let you know I've seen this and will look into it this week. If we can reproduce the defect, we will write an automated test to reproduce, fix it, and if there is a temporary work around till a new release is available, provide it to you.

**Comment by ericfranz** [comment]
I have confirmed that if the cluster config does not specify in the metadata section a title, the fallback code to produce the title string results in a crash because the code assumes the id is a string, but it is a symbol. #400 is a temporary fix but https://github.com/OSC/ood_core/issues/98 is a long term fix.

For your scenario, will you check your cluster config files and see if there are any titles missing from them, and if so add them? An example from https://osc.github.io/ood-documentation/release-1.3/installation/add-cluster-config.html would be:

```yaml
---
v2:
  metadata:
    title: "Talapas"
```

**Comment by ericfranz** [comment]
@tutufan let me know if this fixes your problem, and thank you so much for reporting it!

**Comment by tutufan** [comment]
I haven't forgotten this, but it might take a while before I can get back to it.  Thanks!

**Comment by tutufan** [comment]
It's a bit embarrassing, but it turns out that the word `metadata` was misspelled in that YAML config file.  Thanks again!
