### ISSUE TITLE
Developer dashboard crash after clone of repo without manifest

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/ood-dashboard#89]
When using developer tools in dashboard to create a new app.

When `manifest.yml` is not available in a github repo, the dashboard shows an internal server error after clone.

**Comment by basilgohar** [comment]
This is the error I encountered:
```
#<Errno::ENOENT: No such file or directory @ rb_sysopen - /users/appl/bgohar/awesim/dev/eclipse/manifest.yml>

/var/www/ood/apps/sys/dashboard/app/models/product.rb:212:in `initialize'
/var/www/ood/apps/sys/dashboard/app/models/product.rb:212:in `open'
/var/www/ood/apps/sys/dashboard/app/models/product.rb:212:in `write_manifest'
/var/www/ood/apps/sys/dashboard/app/models/product.rb:141:in `update'
/var/www/ood/apps/sys/dashboard/app/controllers/products_controller.rb:61:in `block in update'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/mime_responds.rb:212:in `respond_to'
/var/www/ood/apps/sys/dashboard/app/controllers/products_controller.rb:60:in `update'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
/var/www/ood/apps/sys/dashboard/app/controllers/products_controller.rb:143:in `dispatch'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/lograge-0.4.1/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
/var/www/ood/apps/sys/dashboard/vendor/bundle/ruby/gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
/opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/rack/thread_handler_extension.rb:74:in `process_request'
/opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/request_handler/thread_handler.rb:141:in `accept_and_process_next_request'
/opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/request_handler/thread_handler.rb:109:in `main_loop'
/opt/rh/rh-passenger40/root/usr/share/passenger/phusion_passenger/request_handler.rb:455:in `block (3 levels) in start_threads'

**Comment by nickjer** [comment]
Note, this is due to a broken symlink for the `manifest.yml`.

**Comment by ericfranz** [comment]
Clone a repo that has a symlink to a manifest that doesn't exist. You can probably reproduce this by creating a local copy of an app, `rm manifest.yml` and `ln -s tmp/manifest.yml manifest.yml` and commit that change locally, then put the full path to that local git repo in the form when creating a new app.

**Comment by brianmcmichael** [comment]
I've just confirmed that the outstanding PR at https://github.com/OSC/ood-dashboard/pull/97 also fixes this issue.

After merging #97, instead of getting the `rb_sysopen` error, the app is created and a user error is provided:

![badmanifest](https://cloud.githubusercontent.com/assets/2374718/21624131/c4163e90-d1d3-11e6-866a-fe00271459a6.png)

**Comment by brianmcmichael** [comment]
Closing as #97 has been merged.
